version: "3"
services:
  web:
    image: rishatsharafiev/get-started:part2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    networks:
      - webnet
networks:
  webnet: